### ISSUE TITLE
Please don't touch anything on Vita

### ISSUE THREAD

**Issue by aknight2015** [hatoving/GMSVitaPortInstructions#3]
I've bought the game via Steam and I try to patch it and I get a `An error has occurred: xdelta3: target window checksum mismatch: XD3_INVALID_INPUT` error.

**Comment by hatoving** [comment]
You need to get the Android version in order to patch it for your Vita.
https://play.google.com/store/apps/details?id=com.forwardxp.pdtaclassic&hl=en&gl=US

-hatoving
