### ISSUE TITLE
Please don't touch anything on Vita

### ISSUE THREAD

**Issue by aknight2015** [hatoving/GMSVitaPortInstructions#4]
According to your instructions I patch the renamed data.win.

**Comment by hatoving** [comment]
Uh, yeah.
Why did you open this issue???

-hatoving

**Comment by aknight2015** [comment]
You closed the ticket before I could post a reply. Is the Android version of PDTA the only version your port will work with?

**Comment by hatoving** [comment]
Hi again, yeah, it's the Android version the patch works with.

-hatoving

**Comment by aknight2015** [comment]
Is there anyway for the Steam version of the game to work on the port?

**Comment by hatoving** [comment]
I mean, yeah, there is. However, I already got the game released for the Android version, so there wouldn't be any reason why I would port the same game again just from a different platform.
Also, let's discuss this at Twitter or something, if you have a bug or a request to send, then do that here, please.
Twitter: @hatoving 

I'm gonna close this now.

-hatoving
