### ISSUE TITLE
Fran Bow Chapter 3

### ISSUE THREAD

**Issue by Nanashi13** [hatoving/GMSVitaPortInstructions#5]
Hi, first of all, thank you for all the wonderful ports! It's great that still are people like you bringing content to the PS Vita.
Im opening this issue because i have a problem with Fran Bow Ch. 3. I patched the game.win without problem, but when i want to start a new game, the game gets a black screen, then it appears on the top left corner of the black screen the key icon and i get sound (music plays background) but the screen remains black. I don't know what im doing wrong, i patched the two previous chapters and play them without any issue.
![2021-04-21-2045072](https://user-images.githubusercontent.com/72247318/115635917-1d6eab00-a2e3-11eb-8dc7-88912b06190a.png)

**Comment by hatoving** [comment]
Huh, this is unexpected.
Have you tried re-doing the steps?

-hatoving

**Comment by Nanashi13** [comment]
Yes, i re did the steps 5 times, i even try it on my other PS Vita (i have 2), same result.

**Comment by hatoving** [comment]
Well, either there's one tiny you overlooked or the patch is crappy lol.
You could try checking if the version is correct, the current one compatible is 2.02 i think.
If that still doesn't work, I'll try something else out.

-hatoving

**Comment by Nanashi13** [comment]
Im sure that im using version 2.02. I don't know what's going on, i patched the data just like the 2 previous releases, and both works great. This is the only one that gave me problems. Also, the xdelta patch recognize the version as valid. Still, i will try it again.

**Comment by hatoving** [comment]
I'll update the patch, see if it works.
Except a patch sooner or later, hope it works.
Otherwise, good luck! 👍 

-hatoving

**Comment by Nanashi13** [comment]
Thanks, i will be waiting for the updated patch.

**Comment by hatoving** [comment]
Hey, sorry for not really updating you on the situation. I tried looking into the issue, and I didn't find anything. I really don't know what the problem is, maybe the "data.win" file is a bit broken. If you haven't re-downloaded Fran Bow Chapter 3 yet, then please try that. I can't bring much help.

Best regards, -hat
