### ISSUE TITLE
Request: Deltarune Chapter 1&2

### ISSUE THREAD

**Issue by bertibertig** [hatoving/GMSVitaPortInstructions#8]
Heyo,
I was just wondering if it would be possible to port Deltarune Chapter 1&2 since it's a free demo.
Link: https://tobyfox.itch.io/deltarune

Thanks in advance.

**Comment by hatoving** [comment]
Hi, the demo that's on Itch.io and Steam are not portable since it's made GMS 2.3.

Cheers,
hatoving
